DEVICE = {
    "driver": "pico_display_2",
    "page_profile": "pico-display-2-landscape",
    "rotation": 0,
    "backlight": 0.7,
    "font": "bitmap8",
    "serial_fallback": True,
}

MQTT = {
    "host": "192.168.1.10",
    "port": 1883,
    "base_topic": "inkplate/weather-calendar",
    "client_id": "weather-cal-pico-display-2",
    "keepalive_s": 60,
    "reconnect_min_s": 2,
    "reconnect_max_s": 60,
    "diagnostics": {
        "enabled": True,
        "status_interval_s": 300,
    },
}

RUNTIME = {
    "default_page_duration_s": 8,
    "redraw_coalesce_ms": 250,
    "forced_refresh_s": 300,
    "stale_after_s": 14400,
    "button_debounce_ms": 180,
    "message_mode": "event",
    "event_wait_ms": 1000,
    "loop_sleep_ms": 50,
}

BUTTONS = {
    "previous": {"pin": 14, "active_low": True},
    "next": {"pin": 15, "active_low": True},
    "home": {"pin": 12, "active_low": True},
    "pause": {"pin": 13, "active_low": True},
}

PAGES = [
    {
        "id": "now",
        "duration_s": 10,
        "widgets": [
            {
                "type": "text",
                "text": "WEATHER",
                "x": 10,
                "y": 8,
                "scale": 3,
                "color": "cyan",
            },
            {
                "type": "weather_alert",
                "x": 236,
                "y": 10,
                "scale": 2,
                "color": "red",
            },
            {
                "type": "icon",
                "path": "current.icon",
                "x": 18,
                "y": 54,
                "scale": 4,
            },
            {
                "type": "value",
                "path": "current.temperature",
                "formatter": "temperature",
                "x": 100,
                "y": 54,
                "scale": 5,
                "color": "white",
            },
            {
                "type": "value",
                "path": "current.humidity",
                "formatter": "percent",
                "label": "HUM ",
                "x": 102,
                "y": 105,
                "scale": 2,
                "color": "muted",
                "missing": None,
            },
            {
                "type": "value",
                "path": "wind",
                "formatter": "wind",
                "x": 12,
                "y": 157,
                "scale": 2,
                "card": True,
                "card_x": 8,
                "card_y": 148,
                "card_width": 304,
                "card_height": 36,
            },
            {
                "type": "value",
                "path": "rain",
                "formatter": "rain",
                "label": "RAIN ",
                "x": 12,
                "y": 202,
                "scale": 2,
                "card": True,
                "card_x": 8,
                "card_y": 193,
                "card_width": 304,
                "card_height": 36,
            },
        ],
    },
    {
        "id": "forecast",
        "duration_s": 9,
        "widgets": [
            {
                "type": "text",
                "text": "FORECAST",
                "x": 10,
                "y": 8,
                "scale": 3,
                "color": "cyan",
            },
            {
                "type": "hourly_table",
                "x": 8,
                "y": 48,
                "width": 304,
                "rows": 4,
                "row_height": 47,
            },
        ],
    },
    {
        "id": "system",
        "widgets": [
            {
                "type": "text",
                "text": "SYSTEM",
                "x": 10,
                "y": 8,
                "scale": 3,
                "color": "cyan",
            },
            {
                "type": "metadata",
                "x": 12,
                "y": 62,
                "scale": 2,
                "card": True,
                "card_x": 8,
                "card_y": 52,
                "card_width": 304,
                "card_height": 38,
            },
            {
                "type": "server_status",
                "x": 12,
                "y": 112,
                "scale": 2,
                "card": True,
                "card_x": 8,
                "card_y": 102,
                "card_width": 304,
                "card_height": 38,
            },
            {
                "type": "value",
                "path": "server.runtime.version",
                "label": "VERSION ",
                "x": 12,
                "y": 162,
                "scale": 2,
                "missing": "unknown",
                "card": True,
                "card_x": 8,
                "card_y": 152,
                "card_width": 304,
                "card_height": 38,
            },
            {
                "type": "text",
                "text": "A HOME  B PAUSE  X/Y NAV",
                "x": 12,
                "y": 214,
                "scale": 1,
                "color": "muted",
            },
        ],
    },
]

PAGE_PROFILES = {"pico-display-2-landscape": PAGES}
